### ISSUE TITLE
Case-insensitive command names/aliases

### ISSUE THREAD

**Issue by ghost** [janluke/cloup#101]
It would be nice to have an option to make command names and aliases case-insensitive. For now, I implemented this in my code by stealing `CaseInsensitiveDict` from `requests`, but it can probably be implemented natively without that dependency.

```py
from requests.utils import CaseInsensitiveDict


class CaseInsensitiveGroup(cloup.Group):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.alias2name = CaseInsensitiveDict()
```

**Comment by janluke** [comment]
https://click.palletsprojects.com/en/8.0.x/advanced/#token-normalization

**Comment by ghost** [comment]
I know about `token_normalize_func`, but that's too generic and provides no context about where the value came from. For example, it breaks if you have both `-a` and `-A` as distinct options.

**Comment by janluke** [comment]
Yes, there's not fine-grained control with `token-normalization`. But I have two questions:
1. why should someone type a command name using uppercase letters or mixed-case letters?
2. isn't slightly inconsistent to have case-insensitive commands but case-sensitive options?

I'm not very keen to add this feature because it seems not very relevant for most people. If it was common to use camel-case for command names, maybe it'd be a useful feature but that's not the case. The convention is to snake_case or kebab-case for commands.

**Comment by ghost** [comment]
If you don't think it's a useful feature, that's fine, I'll just keep my hack in my code. But `click.Choice` also has a `case_sensitive` option independent of `token_normalize_func`.

And you're right, for the average CLI program you're unlikely to need anything more than lowercase command names with underscores or hyphens. But the program I'm writing is a downloader, and subcommands are names of websites/services (minus spaces, of course), and it looks much better in the help if the names aren't all lowercase.

**Comment by janluke** [comment]
I thought of choices but in that case it makes sense because those are _values_, they are NOT subjected to a naming convention :).

> But the program I'm writing is a downloader, and subcommands are names of websites/services

Oh, that's interesting. Do you have a public repo for this program?

**Comment by janluke** [comment]
Can't you lower-case them by the way? I would do that. I wouldn't call a command  `YouTube`, I would call it `youtube`.

**Comment by janluke** [comment]
Closingy. If it turns out a consistent number of people want this feature, I'll add it.
