### ISSUE TITLE
Allow `params` attribute in decorators 

### ISSUE THREAD

**Issue by kdeldycke** [janluke/cloup#108]
To mimick the new feature introduced in `click 8.1.0` can we allow `cloup.command` and `cloup.group` to accept a `params` argument?

See:
* https://github.com/pallets/click/issues/2131
* https://github.com/pallets/click/pull/2203

**Comment by janluke** [comment]
Hey @kdeldycke! Sorry for the delay. Of course, this is less important for Cloup users since they can enjoy autocomplete from decorator and use `option_group` to easily share a set of arguments but I think this should be added if Click supports it and it's anyway a nice-to-have. Would you like to contribute yourself? It'd be great to have an experienced contributor!

**Comment by janluke** [comment]
Actually this is already supported as long as you use click >= 8.1.0. But you'd probably get a mypy error. For some reason, all the overloads for `cls: None` do not include `**kwargs`. I  think there was a reason for that but I can't remember it now.

**Comment by kdeldycke** [comment]
Thanks @janluke for the update. With the release of Cloup v1.0.0 I managed to [refactor click-extra to use the declarative `params=` argument](https://github.com/kdeldycke/click-extra/blob/67f92f46c861666dfac5ef9408486d2940496f64/click_extra/commands.py#L175-L191).
