### ISSUE TITLE
Highlights options, choices and metavars

### ISSUE THREAD

**Issue by kdeldycke** [janluke/cloup#95]
I just discovered `cloup` and it is fantastic! It's basically an up-to-date bundle of all the [unmaintained `click-contrib`](https://github.com/click-contrib/) utilities! 😍

I developed some code in my [`mail-deduplicate` CLI](https://github.com/kdeldycke/mail-deduplicate) some month ago to automatically highlights all options, choices and metavars in help screens generated by click. See how it renders:

![cli-colored-help](https://user-images.githubusercontent.com/159718/136374271-357130c1-07d9-4d37-a506-4f256e5d6ecf.png)

For reference, here is my current implementation: https://github.com/kdeldycke/mail-deduplicate/blob/develop/mail_deduplicate/colorize.py

@janluke, would you be interested by my attempt at integrating my extra-highlight logic into `cloup`'s help formatting code?

**Comment by janluke** [comment]
> I just discovered cloup and it is fantastic! 

Thank you! Glad you like it!

> would you be interested by my attempt at integrating my extra-highlight logic into cloup's help formatting code?

A more fine-grained theming (metavars and defaults) was something I tried to implement when I first introduced the theming feature! Unfortunately, click is not very well designed when it comes to formatting. Formatting logic is splitted in many components and the so called `HelpFormatter` is just a low-level formatter. So I ultimately decided to give up or at least to leave a more fine-grained formatting for the future at the time. Even because, in theory, Click should get a new formatting system soon or later (though I'm starting to doubt it'll ever come out), so I didn't want to waste too much time on the current one.

Coming to you proposal, I'm all in for adding the feature, of course, but using regular expressions looks more like a workaround to me :(

**Comment by kdeldycke** [comment]
> A more fine-grained theming (metavars and defaults) was something I tried to implement when I first introduced the theming feature!

Aha, great minds think alike! I guess we both reached the conclusion that finer highlighting increase the readability of help screens.

I just had a look at your bug reports and PRs to Click project. And realized how much work it takes to already have that flexible help in Cloup. Thanks a lot for your dedication and thanks for making Click better!

Now for that extra-highlighting. I understand you do not want to taint Cloup's clean code with ugly regexps. 😉 My rationale was that help screen are not consumed by machine but are designed for human. So a hack was good enough and a good compromise.

Ideally we should have proper fine-grained support of semantics in Click. I guess this is more or less covered by that mega-issue: https://github.com/pallets/click/issues/561

Anyway, feel free to close this issue if it doesn't make sense. I think I'll still try to piggy-back on Cloup in my CLIs and re-adapt my regexps to its logic (depending on my motivation).

**Comment by janluke** [comment]
> Aha, great minds think alike! 

;)

> I just had a look at your bug reports and PRs to Click project. And realized how much work it takes to already have that flexible help in Cloup. Thanks a lot for your dedication and thanks for making Click better!

Thank you, I appreciate it! It was a lot of work indeed.

> Now for that extra-highlighting. I understand you do not want to taint Cloup's clean code with ugly regexps. 😉 My rationale was that help screen are not consumed by machine but are designed for human. So a hack was good enough and a good compromise.

It's totally okay to do that at the application level but it's still a workaround. I've made use of workarounds in Cloup but in this case "there must be a better way" ([quote](https://fullstackfeed.com/there-must-be-a-better-way-raymond-hettinger-python/)). 

Furthermore, I was thinking that maybe rather than improving the console help page, it's better to invest time in generating HTML documentation / man pages and opening the browser when the user runs `--help` (if there is a browser), as `git` does. 

> Anyway, feel free to close this issue if it doesn't make sense.

I'll close this issue and open a new one that references this one, since I'm open to include the feature. Unfortunately I've no time for this right now :(.

**Comment by kdeldycke** [comment]
FYI, I just release [`click-extra`](https://github.com/kdeldycke/click-extra) with all my additional help screen colorization code. It might need some polishing but it is good enough and reasonably tested to be used by others.
